AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LambdaJavaLhaFunction

Globals:
  Function:
    Runtime: java8
    CodeUri: app/
    MemorySize: 128
    Timeout: 900

Resources:
  LambdaJavaLhaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LambdaJavaLhaFunction
      Handler: lha.App::handleRequest
